name: oberhauser_dev
description: Web presence of Oberhauser Development.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.0.6
  flutter_svg: ^2.0.4
  flutter_lints: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - fonts/devicon.ttf
    - assets/images/Oberhauser-Dev-simple-sw.svg
    - assets/images/Silberperlen.jpg
    - assets/images/projects/AppInsGruene_Logo.svg
    - assets/images/projects/GB-FullCalendar.svg
    - assets/images/projects/Naturfreunde_SkiAlpin_Logo_dark.svg
    - assets/images/projects/MemeGenerator.svg
    - assets/images/projects/Oberhauser-Dev-simple.svg
    - assets/images/projects/TSV_Aichach_Favicon_Red.svg
    - assets/images/projects/TSV_Aichach_Wrestling_Invert.svg
  fonts:
    - family: Devicon
      fonts:
      - asset: fonts/devicon.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand.ttf
